plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.screenshot)
}

android {
    experimentalProperties["android.experimental.enableScreenshotTest"] = true

    namespace = "com.example.aura"
    compileSdk {
        version = release(36)
    }

    defaultConfig {
        applicationId = "com.example.aura"
        minSdk = 31
        targetSdk = 36
        versionCode = 1
        versionName = "1.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
    buildFeatures {
        compose = true
    }
}

dependencies {
    implementation(libs.aura.shared)

    implementation(platform(libs.androidx.compose.bom))

    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.runtime.ktx)

    implementation(libs.bundles.coil)
    implementation(libs.bundles.media3)
    implementation(libs.bundles.nav3)
    implementation(libs.bundles.compose)
    implementation(libs.bundles.koin)

    implementation(libs.androidx.splashscreen)
    implementation(libs.kotlinx.serialization.json)
    implementation(libs.androidx.compose.material3.adaptive.navigation.suite)
    implementation(libs.androidx.compose.material3)
    implementation(libs.adaptive)

    implementation(libs.orbit.core)
    implementation(libs.orbit.viewmodel)
    implementation(libs.orbit.compose)

    testImplementation(libs.junit)
    androidTestImplementation(libs.androidx.junit)
    androidTestImplementation(libs.androidx.espresso.core)
    androidTestImplementation(platform(libs.androidx.compose.bom))
    androidTestImplementation(libs.androidx.compose.ui.test.junit4)
    debugImplementation(libs.androidx.compose.ui.tooling)
    debugImplementation(libs.androidx.compose.ui.test.manifest)

    screenshotTestImplementation(libs.screenshot.validation.api)
    screenshotTestImplementation(libs.androidx.compose.ui.tooling)

    testImplementation(libs.mockk)
    testImplementation(libs.kotlinx.coroutines.test)
    testImplementation(libs.turbine)
    testImplementation(libs.orbit.test)
}


tasks.register("updateScreenshotGallery") {
    group = "verification"
    description = "Updates SCREENSHOTS.md with the latest reference images."

    // Capture paths at configuration time
    val referenceDir = layout.projectDirectory.dir("src/screenshotTestDebug/reference").asFile
    val rootDir = layout.projectDirectory.dir("..").asFile
    val outputFile = File(rootDir, "SCREENSHOTS.md")

    doLast {
        if (!referenceDir.exists()) {
            println("Reference directory not found: ${referenceDir.absolutePath}")
            return@doLast
        }

        val sb = StringBuilder()
        sb.append("# Screenshot Gallery\n\n")
        sb.append("This file is automatically generated. To update it, run `./gradlew updateScreenshotGallery`.\n\n")

        // Find all directories that contain PNG files (regardless of depth)
        val screenshotDirs = referenceDir.walkTopDown()
            .filter { it.isDirectory && it.listFiles()?.any { file -> file.extension == "png" } == true }
            .sortedBy { it.name }
            .toList()

        if (screenshotDirs.isEmpty()) {
            sb.append("*No screenshots found.*\n")
        }

        screenshotDirs.forEach { dir ->
            val className = dir.name
                .removeSuffix("Kt")
                .removeSuffix("ScreenshotTest")
                .removeSuffix("Preview")
                .replace(Regex("([a-z])([A-Z])"), "$1 $2")

            sb.append("## $className\n\n")

            val images = dir.listFiles { file -> file.extension == "png" }?.sortedBy { it.name } ?: emptyList()

            sb.append("| State | Screenshot |\n")
            sb.append("| :--- | :--- |\n")

            images.forEach { image ->
                val label = image.name
                    .replace(Regex("_[a-f0-9]{8}_\\d+\\.png$"), "")
                    .removeSuffix("ScreenshotTest")
                    .replace(Regex("([a-z])([A-Z])"), "$1 $2")
                val relativePath = image.relativeTo(rootDir).path.replace("\\", "/")
                sb.append("| $label | ![$label]($relativePath) |\n")
            }
            sb.append("\n")
        }

        outputFile.writeText(sb.toString())
        println("Gallery generated: ${outputFile.absolutePath}")
        println("Found ${screenshotDirs.size} screenshot test classes with ${screenshotDirs.sumOf { it.listFiles()?.count { f -> f.extension == "png" } ?: 0 }} images")
    }
}

// Wait until after project evaluation to configure the finalization
afterEvaluate {
    tasks.named("updateDebugScreenshotTest") {
        finalizedBy("updateScreenshotGallery")
    }
}
